alias art='php artisan'
alias artdebug='php -dxdebug.mode=debug -dxdebug.client_host=host.docker.internal -dxdebug.client_port=9003 -dxdebug.start_with_request=yes artisan'
alias dev='./rundev'
alias devrev='./rundev-reverb'
alias compdev='./composer-dev'
alias dbuild='docker run --rm -it $(docker build -q .) bash'
